### ISSUE TITLE
array_key_exists Error when YAML is correct but is missing Application logic

### ISSUE THREAD

**Issue by martialblog** [Icinga/icingaweb2-module-toplevelview#69]
array_key_exists(): Argument #2 ($array) must be of type array, string given

```
---
name: "example"
set_downtime_if_notification_disabled: true
children:
  - name: "Example"
    children:
      name: foobar
```
